### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ihayhurst** [Dragon8oy/kernel-notify#2]
Starting Kernel-notify from command line, calls id for username but truncates it to 8 characters (thus not locating a valid username)

Checking latest version...
Latest Kernel: 5.3.7
Current Kernel: 5.3.1
Kernel 5.3.7 is available, You are currently running Kernel 5.3.1 
id: ‘ihayhurs’: no such user

**Comment by stuarthayhurst** [comment]
Issue with `w -oush` truncating. Replaced with who and fixed in v5.6.1
