### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ihayhurst** [Dragon8oy/kernel-notify#3]
**Describe the bug**

**To Reproduce**
kernel-notify -r
(specified to remove kernels 4 and 5 ) uses a space as a separator
outpt:
Checking latest version...
Currently installed kernels:
     1	5.3.0-23
     2	5.3.0-24
     3	5.3.13-050313
     4	5.3.7-050307
     5	5.3.8-050308
     6	5.4.2-050402
The config is set to keep 5 kernels before notifying users
Please enter the kernels or numbers you want to remove: (x.x.x-xXxXxX): 
4 5
./actions: line 165: [[: 4 5: syntax error in expression (error token is "5")
Are you sure you want to remove kernel(s): 5.3.7-050307 5.3.8-050308? [y/N] y

**Expected behavior**
program continued despite error, 

*

**System Information**
Program Version: Kernel-notify version: 5.8
Distro:
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
ihayhurst@Aconite:~$cat /etc/debian_version 
buster/sid
ihayhurst@Aconite:~$uname -a
Linux Aconite 5.3.13-050313-generic #201911240840 SMP Sun Nov 24 08:43:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Are the optional dependencies installed? [Yes / No]

**Additional context**

**Comment by stuarthayhurst** [comment]
Broken if statement throwing an error when multiple kernels are to be removed

Fixed by commit 949d67b7ad162a0757f262a2e28e952b9029f019
Released in Patch Release v5.8.1
